import { LayerConfig } from './types';

export const LAYER_CONFIGS: LayerConfig[] = [
  {
    id: 'OIL_RIGS',
    nameKey: 'layers.oilRigs',
    serviceUrl: process.env.NEXT_PUBLIC_LAYER_OIL_RIGS ?? '',
    priority: 'P0',
    color: '#1A6B5C',
    symbolType: 'point',
    defaultVisible: true,
    deferred: false,
  },
  {
    id: 'OIL_WELLS',
    nameKey: 'layers.oilWells',
    serviceUrl: process.env.NEXT_PUBLIC_LAYER_OIL_WELLS ?? '',
    priority: 'P0',
    color: '#E8A020',
    symbolType: 'point',
    defaultVisible: true,
    deferred: false,
  },
  {
    id: 'CALENVIRO',
    nameKey: 'layers.pm25',
    serviceUrl: process.env.NEXT_PUBLIC_LAYER_PM25 ?? '',
    priority: 'P0',
    color: '#1A6B5C',
    symbolType: 'polygon',
    defaultVisible: true,
    deferred: false,
  },
  {
    id: 'PIPELINE',
    nameKey: 'layers.pipeline',
    serviceUrl: process.env.NEXT_PUBLIC_LAYER_PIPELINE ?? '',
    priority: 'P0',
    color: '#CC5028',
    symbolType: 'polyline',
    defaultVisible: true,
    deferred: false,
  },
  {
    id: 'INDIGENOUS',
    nameKey: 'layers.indigenous',
    serviceUrl: process.env.NEXT_PUBLIC_LAYER_INDIGENOUS ?? '',
    priority: 'P1',
    color: '#B4783C',
    symbolType: 'polygon',
    defaultVisible: true,
    deferred: false,
  },
  {
    id: 'ORGS',
    nameKey: 'layers.orgs',
    serviceUrl: process.env.NEXT_PUBLIC_LAYER_ORGS ?? '',
    priority: 'P1',
    color: '#4A5080',
    symbolType: 'point',
    defaultVisible: false,
    deferred: false,
  },
  {
    id: 'NEWS',
    nameKey: 'layers.news',
    serviceUrl: '',
    priority: 'P1',
    color: '#CC3333',
    symbolType: 'point',
    defaultVisible: true,
    deferred: false,
  },
];
